/** \file
 *  This C source file was generated by $ANTLR version 3.2 debian-14
 *
 *     -  From the grammar source file : rnbw.g
 *     -                            On : 2017-11-04 15:22:09
 *     -                 for the lexer : rnbwLexerLexer *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "rnbwLexer.h"
/* ----------------------------------------- */


/** String literals used by rnbwLexer that we must do things like MATCHS() with.
 *  C will normally just lay down 8 bit characters, and you can use L"xxx" to
 *  get wchar_t, but wchar_t is 16 bits on Windows, which is not UTF32 and so
 *  we perform this little trick of defining the literals as arrays of UINT32
 *  and passing in the address of these.
 */
static ANTLR3_UCHAR	lit_1[]  = { 0x2D, 0x68,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_2[]  = { 0x2D, 0x2D, 0x68, 0x65, 0x6C, 0x70,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_3[]  = { 0x68, 0x65, 0x6C, 0x70,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_4[]  = { 0x2D, 0x63,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_5[]  = { 0x2D, 0x2D, 0x63, 0x6F, 0x6C, 0x6F, 0x72, 0x73,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_6[]  = { 0x2D, 0x70,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_7[]  = { 0x2D, 0x2D, 0x70, 0x61, 0x74, 0x68,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_8[]  = { 0x2D, 0x77,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_9[]  = { 0x2D, 0x2D, 0x77, 0x69, 0x64, 0x74, 0x68,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_10[]  = { 0x2D, 0x61,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_11[]  = { 0x2D, 0x2D, 0x61, 0x6E, 0x67, 0x6C, 0x65,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_12[]  = { 0x2D, 0x66,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_13[]  = { 0x2D, 0x2D, 0x66, 0x69, 0x6C, 0x65,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_14[]  = { 0x72, 0x67, 0x62,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_15[]  = { 0x72, 0x62, 0x67,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_16[]  = { 0x67, 0x72, 0x62,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_17[]  = { 0x67, 0x62, 0x72,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_18[]  = { 0x62, 0x72, 0x67,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_19[]  = { 0x62, 0x67, 0x72,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_20[]  = { 0x6C, 0x69, 0x6E, 0x65,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_21[]  = { 0x79, 0x61, 0x72, 0x6E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_22[]  = { 0x65, 0x64, 0x67, 0x65, 0x73,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_23[]  = { 0x66, 0x72, 0x6F, 0x6D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_24[]  = { 0x69, 0x6E, 0x63, 0x6C, 0x75, 0x64, 0x69, 0x6E, 0x67,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_25[]  = { 0x6E, 0x6F, 0x74,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_26[]  = { 0x74, 0x6F,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_27[]  = { 0x62, 0x61, 0x63, 0x6B,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_28[]  = { 0x61, 0x6E, 0x64,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_29[]  = { 0x2D, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_30[]  = { 0x3C, 0x2D, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_31[]  = { 0x3C, 0x69, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_32[]  = { 0x3C, 0x6E, 0x3E,  ANTLR3_STRING_TERMINATOR};




/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */
 
#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   prnbwLexer_##scope##_SCOPE
#define SCOPE_STACK(scope)  prnbwLexer_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->prnbwLexer_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->prnbwLexer_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

 
/* Macros for accessing things in a lexer
 */
#undef	    LEXER
#undef	    RECOGNIZER		    
#undef	    RULEMEMO		    
#undef	    GETCHARINDEX
#undef	    GETLINE
#undef	    GETCHARPOSITIONINLINE
#undef	    EMIT
#undef	    EMITNEW
#undef	    MATCHC
#undef	    MATCHS
#undef	    MATCHRANGE
#undef	    LTOKEN
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    INPUT
#undef	    STRSTREAM
#undef	    LA
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    LRECOVER
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    BACKTRACKING
#undef		MATCHANY
#undef		MEMOIZE
#undef		HAVEPARSEDRULE
#undef		GETTEXT
#undef		INDEX
#undef		SEEK
#undef		PUSHSTREAM
#undef		POPSTREAM
#undef		SETTEXT
#undef		SETTEXT8

#define	    LEXER					ctx->pLexer
#define	    RECOGNIZER			    LEXER->rec
#define		LEXSTATE				RECOGNIZER->state
#define		TOKSOURCE				LEXSTATE->tokSource
#define	    GETCHARINDEX()			LEXER->getCharIndex(LEXER)
#define	    GETLINE()				LEXER->getLine(LEXER)
#define	    GETTEXT()				LEXER->getText(LEXER)
#define	    GETCHARPOSITIONINLINE() LEXER->getCharPositionInLine(LEXER)
#define	    EMIT()					LEXSTATE->type = _type; LEXER->emit(LEXER)
#define	    EMITNEW(t)				LEXER->emitNew(LEXER, t)
#define	    MATCHC(c)				LEXER->matchc(LEXER, c)
#define	    MATCHS(s)				LEXER->matchs(LEXER, s)
#define	    MATCHRANGE(c1,c2)	    LEXER->matchRange(LEXER, c1, c2)
#define	    MATCHANY()				LEXER->matchAny(LEXER)
#define	    LTOKEN  				LEXSTATE->token
#define	    HASFAILED()				(LEXSTATE->failed == ANTLR3_TRUE)
#define	    BACKTRACKING			LEXSTATE->backtracking
#define	    FAILEDFLAG				LEXSTATE->failed
#define	    INPUT					LEXER->input
#define	    STRSTREAM				INPUT
#define		ISTREAM					INPUT->istream
#define		INDEX()					ISTREAM->index(ISTREAM)
#define		SEEK(n)					ISTREAM->seek(ISTREAM, n)
#define	    EOF_TOKEN				&(LEXSTATE->tokSource->eofToken)
#define	    HASEXCEPTION()			(LEXSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				LEXSTATE->exception
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    LRECOVER()				LEXER->recover(LEXER)
#define	    MARK()					ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define		MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define		HAVEPARSEDRULE(r)		RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		PUSHSTREAM(str)			LEXER->pushCharStream(LEXER, str)
#define		POPSTREAM()				LEXER->popCharStream(LEXER)
#define		SETTEXT(str)			LEXSTATE->text = str
#define		SKIP()					LEXSTATE->token = &(TOKSOURCE->skipToken)
#define		USER1					LEXSTATE->user1
#define		USER2					LEXSTATE->user2
#define		USER3					LEXSTATE->user3
#define		CUSTOM					LEXSTATE->custom
#define		RULEMEMO				LEXSTATE->ruleMemo
#define		DBG						RECOGNIZER->debugger

/* If we have been told we can rely on the standard 8 bit or 16 bit input
 * stream, then we can define our macros to use the direct pointers
 * in the input object, which is much faster than indirect calls. This
 * is really only significant to lexers with a lot of fragment rules (which
 * do not place LA(1) in a temporary at the moment) and even then
 * only if there is a lot of input (order of say 1M or so).
 */
#if	defined(ANTLR3_INLINE_INPUT_ASCII) || defined(ANTLR3_INLINE_INPUT_UTF16)

# ifdef	ANTLR3_INLINE_INPUT_ASCII

/* 8 bit "ASCII" (actually any 8 bit character set) */

#  define	    NEXTCHAR			((pANTLR3_UINT8)(INPUT->nextChar))
#  define	    DATAP				((pANTLR3_UINT8)(INPUT->data))

# else

#  define	    NEXTCHAR			((pANTLR3_UINT16)(INPUT->nextChar)) 
#  define	    DATAP				((pANTLR3_UINT16)(INPUT->data))

# endif

# define	    LA(n) ((NEXTCHAR + n) > (DATAP + INPUT->sizeBuf) ? ANTLR3_CHARSTREAM_EOF : (ANTLR3_UCHAR)(*(NEXTCHAR + n - 1)))
# define	    CONSUME()											\
{																	\
    if	(NEXTCHAR < (DATAP + INPUT->sizeBuf))						\
    {																\
		INPUT->charPositionInLine++;								\
		if  ((ANTLR3_UCHAR)(*NEXTCHAR) == INPUT->newlineChar)		\
		{															\
			INPUT->line++;											\
			INPUT->charPositionInLine	= 0;						\
			INPUT->currentLine		= (void *)(NEXTCHAR + 1);		\
		}															\
		INPUT->nextChar = (void *)(NEXTCHAR + 1);					\
    }																\
}

#else

// Pick up the input character by calling the input stream implementation.
//
#define	    CONSUME()				INPUT->istream->consume(INPUT->istream)
#define	    LA(n)					INPUT->istream->_LA(INPUT->istream, n)

#endif
#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/* Forward declare the locally static matching functions we have generated and any predicate functions.
 */
static ANTLR3_INLINE  void	mT__25    (prnbwLexer ctx);
static ANTLR3_INLINE  void	mT__26    (prnbwLexer ctx);
static ANTLR3_INLINE  void	mT__27    (prnbwLexer ctx);
static ANTLR3_INLINE  void	mT__28    (prnbwLexer ctx);
static ANTLR3_INLINE  void	mT__29    (prnbwLexer ctx);
static ANTLR3_INLINE  void	mT__30    (prnbwLexer ctx);
static ANTLR3_INLINE  void	mT__31    (prnbwLexer ctx);
static ANTLR3_INLINE  void	mT__32    (prnbwLexer ctx);
static ANTLR3_INLINE  void	mT__33    (prnbwLexer ctx);
static ANTLR3_INLINE  void	mT__34    (prnbwLexer ctx);
static ANTLR3_INLINE  void	mT__35    (prnbwLexer ctx);
static ANTLR3_INLINE  void	mT__36    (prnbwLexer ctx);
static ANTLR3_INLINE  void	mT__37    (prnbwLexer ctx);
static ANTLR3_INLINE  void	mT__38    (prnbwLexer ctx);
static ANTLR3_INLINE  void	mT__39    (prnbwLexer ctx);
static ANTLR3_INLINE  void	mT__40    (prnbwLexer ctx);
static ANTLR3_INLINE  void	mT__41    (prnbwLexer ctx);
static ANTLR3_INLINE  void	mT__42    (prnbwLexer ctx);
static ANTLR3_INLINE  void	mT__43    (prnbwLexer ctx);
static ANTLR3_INLINE  void	mT__44    (prnbwLexer ctx);
static ANTLR3_INLINE  void	mT__45    (prnbwLexer ctx);
static ANTLR3_INLINE  void	mT__46    (prnbwLexer ctx);
static ANTLR3_INLINE  void	mT__47    (prnbwLexer ctx);
static ANTLR3_INLINE  void	mT__48    (prnbwLexer ctx);
static ANTLR3_INLINE  void	mT__49    (prnbwLexer ctx);
static ANTLR3_INLINE  void	mT__50    (prnbwLexer ctx);
static ANTLR3_INLINE  void	mT__51    (prnbwLexer ctx);
static ANTLR3_INLINE  void	mT__52    (prnbwLexer ctx);
static ANTLR3_INLINE  void	mT__53    (prnbwLexer ctx);
static ANTLR3_INLINE  void	mT__54    (prnbwLexer ctx);
static ANTLR3_INLINE  void	mT__55    (prnbwLexer ctx);
static ANTLR3_INLINE  void	mT__56    (prnbwLexer ctx);
static ANTLR3_INLINE  void	mT__57    (prnbwLexer ctx);
static ANTLR3_INLINE  void	mT__58    (prnbwLexer ctx);
static ANTLR3_INLINE  void	mT__59    (prnbwLexer ctx);
static ANTLR3_INLINE  void	mT__60    (prnbwLexer ctx);
static ANTLR3_INLINE  void	mT__61    (prnbwLexer ctx);
static ANTLR3_INLINE  void	mT__62    (prnbwLexer ctx);
static ANTLR3_INLINE  void	mID    (prnbwLexer ctx);
static ANTLR3_INLINE  void	mINT    (prnbwLexer ctx);
static ANTLR3_INLINE  void	mFILENAME    (prnbwLexer ctx);
static ANTLR3_INLINE  void	mWS    (prnbwLexer ctx);
static ANTLR3_INLINE  void	mTokens    (prnbwLexer ctx);
static void	rnbwLexerFree(prnbwLexer ctx);

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */



static void
rnbwLexerFree  (prnbwLexer ctx)
{
    LEXER->free(LEXER);
    
    ANTLR3_FREE(ctx);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "rnbw.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}

/** \brief Create a new lexer called rnbwLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \return 
 *     - Success prnbwLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API prnbwLexer rnbwLexerNew         
(pANTLR3_INPUT_STREAM instream)
{
	// See if we can create a new lexer with the standard constructor
	//
	return rnbwLexerNewSSD(instream, NULL);
}

/** \brief Create a new lexer called rnbwLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \param[state] state Previously created shared recognizer stat
 * \return 
 *     - Success prnbwLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API prnbwLexer rnbwLexerNewSSD         
(pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    prnbwLexer ctx; // Context structure we will build and return

    ctx = (prnbwLexer) ANTLR3_CALLOC(1, sizeof(rnbwLexer));

    if  (ctx == NULL)
    {
        // Failed to allocate memory for lexer context
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * in base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 lexer function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function. 
     *
     * We don't use the macros defined in rnbwLexer.h here so you can get a sense
     * of what goes where.
     */
    
    /* Create a base lexer, using the supplied input stream
     */
    ctx->pLexer	= antlr3LexerNewStream(ANTLR3_SIZE_HINT, instream, state);
    
    /* Check that we allocated the memory correctly
     */
    if	(ctx->pLexer == NULL)
    {
		ANTLR3_FREE(ctx);
		return  NULL;
    }
    /* Install the implementation of our rnbwLexer interface
     */
    ctx->mT__25	= mT__25;
    ctx->mT__26	= mT__26;
    ctx->mT__27	= mT__27;
    ctx->mT__28	= mT__28;
    ctx->mT__29	= mT__29;
    ctx->mT__30	= mT__30;
    ctx->mT__31	= mT__31;
    ctx->mT__32	= mT__32;
    ctx->mT__33	= mT__33;
    ctx->mT__34	= mT__34;
    ctx->mT__35	= mT__35;
    ctx->mT__36	= mT__36;
    ctx->mT__37	= mT__37;
    ctx->mT__38	= mT__38;
    ctx->mT__39	= mT__39;
    ctx->mT__40	= mT__40;
    ctx->mT__41	= mT__41;
    ctx->mT__42	= mT__42;
    ctx->mT__43	= mT__43;
    ctx->mT__44	= mT__44;
    ctx->mT__45	= mT__45;
    ctx->mT__46	= mT__46;
    ctx->mT__47	= mT__47;
    ctx->mT__48	= mT__48;
    ctx->mT__49	= mT__49;
    ctx->mT__50	= mT__50;
    ctx->mT__51	= mT__51;
    ctx->mT__52	= mT__52;
    ctx->mT__53	= mT__53;
    ctx->mT__54	= mT__54;
    ctx->mT__55	= mT__55;
    ctx->mT__56	= mT__56;
    ctx->mT__57	= mT__57;
    ctx->mT__58	= mT__58;
    ctx->mT__59	= mT__59;
    ctx->mT__60	= mT__60;
    ctx->mT__61	= mT__61;
    ctx->mT__62	= mT__62;
    ctx->mID	= mID;
    ctx->mINT	= mINT;
    ctx->mFILENAME	= mFILENAME;
    ctx->mWS	= mWS;
    ctx->mTokens	= mTokens;
    
    /** When the nextToken() call is made to this lexer's pANTLR3_TOKEN_SOURCE
     *  it will call mTokens() in this generated code, and will pass it the ctx
     * pointer of this lexer, not the context of the base lexer, so store that now.
     */
    ctx->pLexer->ctx	    = ctx;
    
    /**Install the token matching function
     */
    ctx->pLexer->mTokens = (void (*) (void *))(mTokens);
    
    ctx->getGrammarFileName	= getGrammarFileName;
    ctx->free		= rnbwLexerFree;

    
    


    /* Return the newly built lexer to the caller
     */
    return  ctx;
}

/* =========================================================================
 * DFA tables for the lexer
 */
/** Static dfa state tables for Cyclic dfa:
 *    1:1: Tokens : ( T__25 | T__26 | T__27 | T__28 | T__29 | T__30 | T__31 | T__32 | T__33 | T__34 | T__35 | T__36 | T__37 | T__38 | T__39 | T__40 | T__41 | T__42 | T__43 | T__44 | T__45 | T__46 | T__47 | T__48 | T__49 | T__50 | T__51 | T__52 | T__53 | T__54 | T__55 | T__56 | T__57 | T__58 | T__59 | T__60 | T__61 | T__62 | ID | INT | FILENAME | WS );
 */
static const ANTLR3_INT32 dfa4_eot[144] =
    {
	-1, 24, 36, 36, 36, 36, 36, 36, 36, 47, 36, 36, 36, 51, 36, 36, 54, -1, 
	-1, 58, -1, 36, 59, -1, -1, -1, 60, 24, 67, 68, 69, 70, 71, -1, 36, 36, 
	-1, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, -1, 36, 36, 36, -1, 86, 36, 
	-1, -1, -1, -1, -1, -1, -1, 24, 24, 24, 24, 24, 24, -1, -1, -1, -1, -1, 
	36, 95, 96, 97, 98, 99, 100, 36, 36, 36, 36, 36, 36, 107, -1, 108, 24, 
	24, 24, 24, 24, 24, 115, -1, -1, -1, -1, -1, -1, 116, 117, 118, 36, 120, 
	36, -1, -1, 24, 24, 24, 24, 24, 24, -1, -1, -1, -1, 128, -1, 36, 130, 24, 
	132, 24, 24, 135, -1, 36, -1, 24, -1, 138, 139, -1, 36, 141, -1, -1, 36, 
	-1, 143, -1
    };
static const ANTLR3_INT32 dfa4_eof[144] =
    {
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1
    };
static const ANTLR3_INT32 dfa4_min[144] =
    {
	9, 45, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, -1, 
	45, 32, -1, 32, 32, -1, -1, -1, 32, 97, 32, 32, 32, 32, 32, -1, 32, 32, 
	-1, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, -1, 32, 32, 32, -1, 32, 32, 
	-1, -1, -1, -1, -1, -1, -1, 101, 111, 97, 105, 110, 105, -1, -1, -1, -1, 
	-1, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, -1, 32, 108, 
	108, 116, 100, 103, 108, 32, -1, -1, -1, -1, -1, -1, 32, 32, 32, 32, 32, 
	32, -1, -1, 112, 111, 104, 116, 108, 101, -1, -1, -1, -1, 32, -1, 32, 32, 
	114, 32, 104, 101, 32, -1, 32, -1, 115, -1, 32, 32, -1, 32, 32, -1, -1, 
	32, -1, 32, -1
    };
static const ANTLR3_INT32 dfa4_max[144] =
    {
	126, 119, 126, 126, 126, 126, 126, 126, 126, 126, 126, 126, 126, 126, 126, 
	126, 126, -1, 110, 126, -1, 126, 126, -1, -1, -1, 126, 119, 126, 126, 126, 
	126, 126, -1, 126, 126, -1, 126, 126, 126, 126, 126, 126, 126, 126, 126, 
	126, -1, 126, 126, 126, -1, 126, 126, -1, -1, -1, -1, -1, -1, -1, 101, 
	111, 97, 105, 110, 105, -1, -1, -1, -1, -1, 126, 126, 126, 126, 126, 126, 
	126, 126, 126, 126, 126, 126, 126, 126, -1, 126, 108, 108, 116, 100, 103, 
	108, 126, -1, -1, -1, -1, -1, -1, 126, 126, 126, 126, 126, 126, -1, -1, 
	112, 111, 104, 116, 108, 101, -1, -1, -1, -1, 126, -1, 126, 126, 114, 126, 
	104, 101, 126, -1, 126, -1, 115, -1, 126, 126, -1, 126, 126, -1, -1, 126, 
	-1, 126, -1
    };
static const ANTLR3_INT32 dfa4_accept[144] =
    {
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 32, 
	-1, -1, 38, -1, -1, 41, 41, 42, -1, -1, -1, -1, -1, -1, -1, 33, -1, -1, 
	39, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 23, -1, -1, -1, 27, -1, -1, 
	31, 34, 35, 36, 37, 40, 1, -1, -1, -1, -1, -1, -1, 4, 6, 8, 10, 12, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 28, -1, -1, -1, -1, 
	-1, -1, -1, -1, 14, 15, 16, 17, 18, 19, -1, -1, -1, -1, -1, -1, 26, 30, 
	-1, -1, -1, -1, -1, -1, 3, 29, 20, 21, -1, 24, -1, -1, -1, -1, -1, -1, 
	-1, 22, -1, 2, -1, 7, -1, -1, 13, -1, -1, 9, 11, -1, 5, -1, 25
    };
static const ANTLR3_INT32 dfa4_special[144] =
    {	
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1
    };

/** Used when there is no transition table entry for a particular state */
#define dfa4_T_empty	    NULL

static const ANTLR3_INT32 dfa4_T0[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 35, 24, 24, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 24, 24, -1, 24, -1, -1, 24, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, -1, -1, -1, 24, 24, -1, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 49, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T1[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 24, 24, 24, 24, 24, 
	24, 24, 24, 24, 24, 24, 24, 24, 24, 24, -1, 24, -1, -1, 24, 24, 24, 24, 
	24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 
	24, 24, 24, 24, 24, -1, -1, -1, 24, 24, -1, 24, 24, 24, 24, 24, 24, 24, 
	24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 
	24, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T2[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 35, 24, 24, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 24, 24, -1, 24, -1, -1, 24, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, -1, -1, -1, 24, 24, -1, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T3[] =
    {
	65, -1, 62, -1, -1, 66, -1, 61, -1, -1, -1, -1, -1, -1, -1, 63, -1, -1, 
	-1, -1, -1, -1, 64
    };static const ANTLR3_INT32 dfa4_T4[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 35, 24, 24, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 24, 24, -1, 24, -1, -1, 24, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, -1, -1, -1, 24, 24, -1, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 50, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T5[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 35, 24, 24, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 24, 24, -1, 24, -1, -1, 24, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, -1, -1, -1, 24, 24, -1, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 52, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T6[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 35, 24, 24, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 24, 24, -1, 24, -1, -1, 24, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, -1, -1, -1, 24, 24, -1, 35, 73, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T7[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 35, 24, 24, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 24, 24, -1, 24, -1, -1, 24, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, -1, -1, -1, 24, 24, -1, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 53, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T8[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 35, 24, 24, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 24, 24, -1, 24, -1, -1, 24, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, -1, -1, -1, 24, 24, -1, 35, 35, 35, 35, 35, 35, 74, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T9[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 35, 24, 24, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 24, 24, -1, 24, -1, -1, 24, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, -1, -1, -1, 24, 24, -1, 35, 75, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T10[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 35, 24, 24, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 24, 24, -1, 24, -1, -1, 24, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, -1, -1, -1, 24, 24, -1, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 76, 35, 35, 35, 35, 35, 35, 35, 
	35, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T11[] =
    {
	88
    };static const ANTLR3_INT32 dfa4_T12[] =
    {
	109
    };static const ANTLR3_INT32 dfa4_T13[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 35, 24, 24, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 24, 24, -1, 24, -1, -1, 24, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, -1, -1, -1, 24, 24, -1, 35, 35, 35, 35, 35, 35, 77, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T14[] =
    {
	122
    };static const ANTLR3_INT32 dfa4_T15[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 35, 24, 24, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 24, 24, -1, 24, -1, -1, 24, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, -1, -1, -1, 24, 24, -1, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 78, 35, 35, 35, 35, 35, 35, 35, 
	35, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T16[] =
    {
	27, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 33, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 31, -1, 
	28, -1, -1, 32, -1, 26, -1, -1, -1, -1, -1, -1, -1, 29, -1, -1, -1, -1, 
	-1, -1, 30
    };static const ANTLR3_INT32 dfa4_T17[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 35, 24, 24, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 24, 24, -1, 24, -1, -1, 24, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, -1, -1, -1, 24, 24, -1, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 80, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T18[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 35, 24, 24, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 24, 24, -1, 24, -1, -1, 24, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, -1, -1, -1, 24, 24, -1, 35, 35, 35, 35, 102, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T19[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 35, 24, 24, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 24, 24, -1, 24, -1, -1, 24, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, -1, -1, -1, 24, 24, -1, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 81, 35, 35, 35, 35, 35, 35, 35, 
	35, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T20[] =
    {
	89
    };static const ANTLR3_INT32 dfa4_T21[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 35, 24, 24, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 24, 24, -1, 24, -1, -1, 24, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, -1, -1, -1, 24, 24, -1, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 103, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T22[] =
    {
	110
    };static const ANTLR3_INT32 dfa4_T23[] =
    {
	123
    };static const ANTLR3_INT32 dfa4_T24[] =
    {
	131
    };static const ANTLR3_INT32 dfa4_T25[] =
    {
	137
    };static const ANTLR3_INT32 dfa4_T26[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 35, 24, 24, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 24, 24, -1, 24, -1, -1, 24, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, -1, -1, -1, 24, 24, -1, 35, 35, 35, 35, 35, 35, 82, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T27[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 35, 24, 24, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 24, 24, -1, 24, -1, -1, 24, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, -1, -1, -1, 24, 24, -1, 35, 35, 35, 35, 104, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T28[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 35, 24, 24, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 24, 24, -1, 24, -1, -1, 24, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, -1, -1, -1, 24, 24, -1, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 119, 35, 35, 35, 35, 35, 35, 
	35, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T29[] =
    {
	90
    };static const ANTLR3_INT32 dfa4_T30[] =
    {
	111
    };static const ANTLR3_INT32 dfa4_T31[] =
    {
	124
    };static const ANTLR3_INT32 dfa4_T32[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 35, 24, 24, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 24, 24, -1, 24, -1, -1, 24, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, -1, -1, -1, 24, 24, -1, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 83, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T33[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 35, 24, 24, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 24, 24, -1, 24, -1, -1, 24, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, -1, -1, -1, 24, 24, -1, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, 105, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T34[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 35, 24, 24, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 24, 24, -1, 24, -1, -1, 24, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, -1, -1, -1, 24, 24, -1, 35, 35, 84, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T35[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 35, 24, 24, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 24, 24, -1, 24, -1, -1, 24, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, -1, -1, -1, 24, 24, -1, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 106, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T36[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 35, 24, 24, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 24, 24, -1, 24, -1, -1, 24, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, -1, -1, -1, 24, 24, -1, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 121, 35, 35, 35, 35, 
	35, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T37[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 35, 24, 24, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 24, 24, -1, 24, -1, -1, 24, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, -1, -1, -1, 24, 24, -1, 35, 35, 35, 129, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T38[] =
    {
	91
    };static const ANTLR3_INT32 dfa4_T39[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 35, 24, 24, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 24, 24, -1, 24, -1, -1, 24, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, -1, -1, -1, 24, 24, -1, 35, 35, 35, 35, 35, 35, 35, 
	35, 136, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T40[] =
    {
	112
    };static const ANTLR3_INT32 dfa4_T41[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 35, 24, 24, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 24, 24, -1, 24, -1, -1, 24, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, -1, -1, -1, 24, 24, -1, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 140, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T42[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 35, 24, 24, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 24, 24, -1, 24, -1, -1, 24, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, -1, -1, -1, 24, 24, -1, 35, 35, 35, 35, 34, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T43[] =
    {
	125
    };static const ANTLR3_INT32 dfa4_T44[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 35, 24, 24, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 24, 24, -1, 24, -1, -1, 24, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, -1, -1, -1, 24, 24, -1, 35, 35, 35, 35, 35, 35, 142, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T45[] =
    {
	133
    };static const ANTLR3_INT32 dfa4_T46[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 35, 24, 24, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 24, 24, -1, 24, -1, -1, 24, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, -1, -1, -1, 24, 24, -1, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 85, 35, 35, 35, 35, 35, 
	35, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T47[] =
    {
	92
    };static const ANTLR3_INT32 dfa4_T48[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 35, 24, 24, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 24, 24, -1, 24, -1, -1, 24, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, -1, -1, -1, 24, 24, -1, 35, 38, 35, 35, 35, 35, 37, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T49[] =
    {
	113
    };static const ANTLR3_INT32 dfa4_T50[] =
    {
	126
    };static const ANTLR3_INT32 dfa4_T51[] =
    {
	134
    };static const ANTLR3_INT32 dfa4_T52[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 35, 24, 24, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 24, 24, -1, 24, -1, -1, 24, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, -1, -1, -1, 24, 24, -1, 35, 35, 79, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T53[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 35, 24, 24, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 24, 24, -1, 24, -1, -1, 24, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, -1, -1, -1, 24, 24, -1, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 101, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T54[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 35, 24, 24, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 24, 24, -1, 24, -1, -1, 24, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, -1, -1, -1, 24, 24, -1, 35, 35, 35, 87, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T55[] =
    {
	93
    };static const ANTLR3_INT32 dfa4_T56[] =
    {
	114
    };static const ANTLR3_INT32 dfa4_T57[] =
    {
	127
    };static const ANTLR3_INT32 dfa4_T58[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 24, 24, 24, 22, 22, 
	22, 22, 22, 22, 22, 22, 22, 22, 24, 24, -1, 24, -1, -1, 24, 24, 24, 24, 
	24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 
	24, 24, 24, 24, 24, -1, -1, -1, 24, 24, -1, 24, 24, 24, 24, 24, 24, 24, 
	24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 
	24, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T59[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 35, 24, 24, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 24, 24, -1, 24, -1, -1, 24, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, -1, -1, -1, 24, 24, -1, 35, 40, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 39, 35, 35, 35, 35, 35, 35, 35, 
	35, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T60[] =
    {
	55, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, 56, -1, -1, -1, -1, 57
    };static const ANTLR3_INT32 dfa4_T61[] =
    {
	25, 25, -1, -1, 25, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, 23, 13, -1, 24, 24, 24, 24, -1, 16, 19, -1, 24, 9, 
	1, 24, 24, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 24, 24, 18, 24, -1, 
	-1, 24, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 
	21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 17, -1, 20, 24, 24, -1, 15, 5, 
	21, 21, 8, 10, 4, 2, 11, 21, 21, 6, 21, 12, 21, 21, 21, 3, 21, 14, 21, 
	21, 21, 21, 7, 21, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T62[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 35, 24, 24, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 24, 24, -1, 24, -1, -1, 24, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, -1, -1, -1, 24, 24, -1, 43, 35, 35, 35, 35, 35, 42, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 41, 35, 35, 35, 35, 35, 35, 35, 
	35, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T63[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 35, 24, 24, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 24, 24, -1, 24, -1, -1, 24, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, -1, -1, -1, 24, 24, -1, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 72, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T64[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 35, 24, 24, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 24, 24, -1, 24, -1, -1, 24, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, -1, -1, -1, 24, 24, -1, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 94, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T65[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 35, 24, 24, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 24, 24, -1, 24, -1, -1, 24, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, -1, -1, -1, 24, 24, -1, 35, 35, 35, 35, 35, 35, 35, 
	35, 44, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T66[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 35, 24, 24, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 24, 24, -1, 24, -1, -1, 24, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, -1, -1, -1, 24, 24, -1, 45, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T67[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 35, 24, 24, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 24, 24, -1, 24, -1, -1, 24, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, -1, -1, -1, 24, 24, -1, 35, 35, 35, 46, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa4_T68[] =
    {
	24, 24, -1, 24, 24, 24, 24, -1, 24, 24, -1, 24, 24, 35, 24, 24, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 24, 24, -1, 24, -1, -1, 24, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, -1, -1, -1, 24, 24, -1, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 48, 35, 35, 35, 35, 35, 35, 35, 
	35, -1, -1, -1, 24
    };

/* Transition tables are a table of sub tables, with some tables
 * reused for efficiency.
 */
static const ANTLR3_INT32 * const dfa4_transitions[] =
{
    dfa4_T61, dfa4_T16, dfa4_T42, dfa4_T48, dfa4_T59, dfa4_T62, dfa4_T65, 
    dfa4_T66, dfa4_T67, dfa4_T1, dfa4_T68, dfa4_T0, dfa4_T4, dfa4_T1, dfa4_T5, 
    dfa4_T7, dfa4_T1, dfa4_T_empty, dfa4_T60, dfa4_T1, dfa4_T_empty, dfa4_T2, 
    dfa4_T58, dfa4_T_empty, dfa4_T_empty, dfa4_T_empty, dfa4_T1, dfa4_T3, 
    dfa4_T1, dfa4_T1, dfa4_T1, dfa4_T1, dfa4_T1, dfa4_T_empty, dfa4_T63, 
    dfa4_T2, dfa4_T_empty, dfa4_T6, dfa4_T8, dfa4_T9, dfa4_T10, dfa4_T13, 
    dfa4_T15, dfa4_T52, dfa4_T17, dfa4_T19, dfa4_T26, dfa4_T_empty, dfa4_T32, 
    dfa4_T34, dfa4_T46, dfa4_T_empty, dfa4_T2, dfa4_T54, dfa4_T_empty, dfa4_T_empty, 
    dfa4_T_empty, dfa4_T_empty, dfa4_T_empty, dfa4_T_empty, dfa4_T_empty, 
    dfa4_T11, dfa4_T20, dfa4_T29, dfa4_T38, dfa4_T47, dfa4_T55, dfa4_T_empty, 
    dfa4_T_empty, dfa4_T_empty, dfa4_T_empty, dfa4_T_empty, dfa4_T64, dfa4_T2, 
    dfa4_T2, dfa4_T2, dfa4_T2, dfa4_T2, dfa4_T2, dfa4_T53, dfa4_T18, dfa4_T21, 
    dfa4_T27, dfa4_T33, dfa4_T35, dfa4_T2, dfa4_T_empty, dfa4_T2, dfa4_T12, 
    dfa4_T22, dfa4_T30, dfa4_T40, dfa4_T49, dfa4_T56, dfa4_T2, dfa4_T_empty, 
    dfa4_T_empty, dfa4_T_empty, dfa4_T_empty, dfa4_T_empty, dfa4_T_empty, 
    dfa4_T2, dfa4_T2, dfa4_T2, dfa4_T28, dfa4_T2, dfa4_T36, dfa4_T_empty, 
    dfa4_T_empty, dfa4_T14, dfa4_T23, dfa4_T31, dfa4_T43, dfa4_T50, dfa4_T57, 
    dfa4_T_empty, dfa4_T_empty, dfa4_T_empty, dfa4_T_empty, dfa4_T2, dfa4_T_empty, 
    dfa4_T37, dfa4_T1, dfa4_T24, dfa4_T1, dfa4_T45, dfa4_T51, dfa4_T1, dfa4_T_empty, 
    dfa4_T39, dfa4_T_empty, dfa4_T25, dfa4_T_empty, dfa4_T1, dfa4_T1, dfa4_T_empty, 
    dfa4_T41, dfa4_T1, dfa4_T_empty, dfa4_T_empty, dfa4_T44, dfa4_T_empty, 
    dfa4_T2, dfa4_T_empty	
};


/* Declare tracking structure for Cyclic DFA 4
 */
static
ANTLR3_CYCLIC_DFA cdfa4
    =	{
	    4,		    /* Decision number of this dfa	    */
	    /* Which decision this represents:   */
	    (const pANTLR3_UCHAR)"1:1: Tokens : ( T__25 | T__26 | T__27 | T__28 | T__29 | T__30 | T__31 | T__32 | T__33 | T__34 | T__35 | T__36 | T__37 | T__38 | T__39 | T__40 | T__41 | T__42 | T__43 | T__44 | T__45 | T__46 | T__47 | T__48 | T__49 | T__50 | T__51 | T__52 | T__53 | T__54 | T__55 | T__56 | T__57 | T__58 | T__59 | T__60 | T__61 | T__62 | ID | INT | FILENAME | WS );",	
	    (CDFA_SPECIAL_FUNC) antlr3dfaspecialStateTransition,	/* Default special state transition function	*/
	    antlr3dfaspecialTransition,		/* DFA specialTransition is currently just a default function in the runtime */
	    antlr3dfapredict,			/* DFA simulator function is in the runtime */
	    dfa4_eot,	    /* EOT table			    */
	    dfa4_eof,	    /* EOF table			    */
	    dfa4_min,	    /* Minimum tokens for each state    */
	    dfa4_max,	    /* Maximum tokens for each state    */
	    dfa4_accept,	/* Accept table			    */
	    dfa4_special,	/* Special transition states	    */
	    dfa4_transitions	/* Table of transition tables	    */

	};	    
/* End of Cyclic DFA 4
 * ---------------------
 */ 
/* =========================================================================
 * End of DFA tables for the lexer
 */ 

/* =========================================================================
 * Functions to match the lexer grammar defined tokens from the input stream
 */

//   Comes from: 7:7: ( '-h' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__25
 *
 * Looks to match the characters the constitute the token T__25
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__25(prnbwLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__25;
       
    
    // rnbw.g:7:7: ( '-h' )
    // rnbw.g:7:9: '-h'
    {
        MATCHS(lit_1); 
        if  (HASEXCEPTION())
        {
            goto ruleT__25Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__25Ex; /* Prevent compiler warnings */
    ruleT__25Ex: ;

}
// $ANTLR end T__25

//   Comes from: 8:7: ( '--help' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__26
 *
 * Looks to match the characters the constitute the token T__26
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__26(prnbwLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__26;
       
    
    // rnbw.g:8:7: ( '--help' )
    // rnbw.g:8:9: '--help'
    {
        MATCHS(lit_2); 
        if  (HASEXCEPTION())
        {
            goto ruleT__26Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__26Ex; /* Prevent compiler warnings */
    ruleT__26Ex: ;

}
// $ANTLR end T__26

//   Comes from: 9:7: ( 'help' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__27
 *
 * Looks to match the characters the constitute the token T__27
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__27(prnbwLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__27;
       
    
    // rnbw.g:9:7: ( 'help' )
    // rnbw.g:9:9: 'help'
    {
        MATCHS(lit_3); 
        if  (HASEXCEPTION())
        {
            goto ruleT__27Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__27Ex; /* Prevent compiler warnings */
    ruleT__27Ex: ;

}
// $ANTLR end T__27

//   Comes from: 10:7: ( '-c' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__28
 *
 * Looks to match the characters the constitute the token T__28
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__28(prnbwLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__28;
       
    
    // rnbw.g:10:7: ( '-c' )
    // rnbw.g:10:9: '-c'
    {
        MATCHS(lit_4); 
        if  (HASEXCEPTION())
        {
            goto ruleT__28Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__28Ex; /* Prevent compiler warnings */
    ruleT__28Ex: ;

}
// $ANTLR end T__28

//   Comes from: 11:7: ( '--colors' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__29
 *
 * Looks to match the characters the constitute the token T__29
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__29(prnbwLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__29;
       
    
    // rnbw.g:11:7: ( '--colors' )
    // rnbw.g:11:9: '--colors'
    {
        MATCHS(lit_5); 
        if  (HASEXCEPTION())
        {
            goto ruleT__29Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__29Ex; /* Prevent compiler warnings */
    ruleT__29Ex: ;

}
// $ANTLR end T__29

//   Comes from: 12:7: ( '-p' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__30
 *
 * Looks to match the characters the constitute the token T__30
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__30(prnbwLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__30;
       
    
    // rnbw.g:12:7: ( '-p' )
    // rnbw.g:12:9: '-p'
    {
        MATCHS(lit_6); 
        if  (HASEXCEPTION())
        {
            goto ruleT__30Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__30Ex; /* Prevent compiler warnings */
    ruleT__30Ex: ;

}
// $ANTLR end T__30

//   Comes from: 13:7: ( '--path' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__31
 *
 * Looks to match the characters the constitute the token T__31
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__31(prnbwLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__31;
       
    
    // rnbw.g:13:7: ( '--path' )
    // rnbw.g:13:9: '--path'
    {
        MATCHS(lit_7); 
        if  (HASEXCEPTION())
        {
            goto ruleT__31Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__31Ex; /* Prevent compiler warnings */
    ruleT__31Ex: ;

}
// $ANTLR end T__31

//   Comes from: 14:7: ( '-w' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__32
 *
 * Looks to match the characters the constitute the token T__32
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__32(prnbwLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__32;
       
    
    // rnbw.g:14:7: ( '-w' )
    // rnbw.g:14:9: '-w'
    {
        MATCHS(lit_8); 
        if  (HASEXCEPTION())
        {
            goto ruleT__32Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__32Ex; /* Prevent compiler warnings */
    ruleT__32Ex: ;

}
// $ANTLR end T__32

//   Comes from: 15:7: ( '--width' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__33
 *
 * Looks to match the characters the constitute the token T__33
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__33(prnbwLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__33;
       
    
    // rnbw.g:15:7: ( '--width' )
    // rnbw.g:15:9: '--width'
    {
        MATCHS(lit_9); 
        if  (HASEXCEPTION())
        {
            goto ruleT__33Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__33Ex; /* Prevent compiler warnings */
    ruleT__33Ex: ;

}
// $ANTLR end T__33

//   Comes from: 16:7: ( '-a' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__34
 *
 * Looks to match the characters the constitute the token T__34
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__34(prnbwLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__34;
       
    
    // rnbw.g:16:7: ( '-a' )
    // rnbw.g:16:9: '-a'
    {
        MATCHS(lit_10); 
        if  (HASEXCEPTION())
        {
            goto ruleT__34Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__34Ex; /* Prevent compiler warnings */
    ruleT__34Ex: ;

}
// $ANTLR end T__34

//   Comes from: 17:7: ( '--angle' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__35
 *
 * Looks to match the characters the constitute the token T__35
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__35(prnbwLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__35;
       
    
    // rnbw.g:17:7: ( '--angle' )
    // rnbw.g:17:9: '--angle'
    {
        MATCHS(lit_11); 
        if  (HASEXCEPTION())
        {
            goto ruleT__35Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__35Ex; /* Prevent compiler warnings */
    ruleT__35Ex: ;

}
// $ANTLR end T__35

//   Comes from: 18:7: ( '-f' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__36
 *
 * Looks to match the characters the constitute the token T__36
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__36(prnbwLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__36;
       
    
    // rnbw.g:18:7: ( '-f' )
    // rnbw.g:18:9: '-f'
    {
        MATCHS(lit_12); 
        if  (HASEXCEPTION())
        {
            goto ruleT__36Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__36Ex; /* Prevent compiler warnings */
    ruleT__36Ex: ;

}
// $ANTLR end T__36

//   Comes from: 19:7: ( '--file' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__37
 *
 * Looks to match the characters the constitute the token T__37
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__37(prnbwLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__37;
       
    
    // rnbw.g:19:7: ( '--file' )
    // rnbw.g:19:9: '--file'
    {
        MATCHS(lit_13); 
        if  (HASEXCEPTION())
        {
            goto ruleT__37Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__37Ex; /* Prevent compiler warnings */
    ruleT__37Ex: ;

}
// $ANTLR end T__37

//   Comes from: 20:7: ( 'rgb' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__38
 *
 * Looks to match the characters the constitute the token T__38
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__38(prnbwLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__38;
       
    
    // rnbw.g:20:7: ( 'rgb' )
    // rnbw.g:20:9: 'rgb'
    {
        MATCHS(lit_14); 
        if  (HASEXCEPTION())
        {
            goto ruleT__38Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__38Ex; /* Prevent compiler warnings */
    ruleT__38Ex: ;

}
// $ANTLR end T__38

//   Comes from: 21:7: ( 'rbg' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__39
 *
 * Looks to match the characters the constitute the token T__39
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__39(prnbwLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__39;
       
    
    // rnbw.g:21:7: ( 'rbg' )
    // rnbw.g:21:9: 'rbg'
    {
        MATCHS(lit_15); 
        if  (HASEXCEPTION())
        {
            goto ruleT__39Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__39Ex; /* Prevent compiler warnings */
    ruleT__39Ex: ;

}
// $ANTLR end T__39

//   Comes from: 22:7: ( 'grb' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__40
 *
 * Looks to match the characters the constitute the token T__40
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__40(prnbwLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__40;
       
    
    // rnbw.g:22:7: ( 'grb' )
    // rnbw.g:22:9: 'grb'
    {
        MATCHS(lit_16); 
        if  (HASEXCEPTION())
        {
            goto ruleT__40Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__40Ex; /* Prevent compiler warnings */
    ruleT__40Ex: ;

}
// $ANTLR end T__40

//   Comes from: 23:7: ( 'gbr' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__41
 *
 * Looks to match the characters the constitute the token T__41
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__41(prnbwLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__41;
       
    
    // rnbw.g:23:7: ( 'gbr' )
    // rnbw.g:23:9: 'gbr'
    {
        MATCHS(lit_17); 
        if  (HASEXCEPTION())
        {
            goto ruleT__41Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__41Ex; /* Prevent compiler warnings */
    ruleT__41Ex: ;

}
// $ANTLR end T__41

//   Comes from: 24:7: ( 'brg' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__42
 *
 * Looks to match the characters the constitute the token T__42
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__42(prnbwLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__42;
       
    
    // rnbw.g:24:7: ( 'brg' )
    // rnbw.g:24:9: 'brg'
    {
        MATCHS(lit_18); 
        if  (HASEXCEPTION())
        {
            goto ruleT__42Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__42Ex; /* Prevent compiler warnings */
    ruleT__42Ex: ;

}
// $ANTLR end T__42

//   Comes from: 25:7: ( 'bgr' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__43
 *
 * Looks to match the characters the constitute the token T__43
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__43(prnbwLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__43;
       
    
    // rnbw.g:25:7: ( 'bgr' )
    // rnbw.g:25:9: 'bgr'
    {
        MATCHS(lit_19); 
        if  (HASEXCEPTION())
        {
            goto ruleT__43Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__43Ex; /* Prevent compiler warnings */
    ruleT__43Ex: ;

}
// $ANTLR end T__43

//   Comes from: 26:7: ( 'line' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__44
 *
 * Looks to match the characters the constitute the token T__44
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__44(prnbwLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__44;
       
    
    // rnbw.g:26:7: ( 'line' )
    // rnbw.g:26:9: 'line'
    {
        MATCHS(lit_20); 
        if  (HASEXCEPTION())
        {
            goto ruleT__44Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__44Ex; /* Prevent compiler warnings */
    ruleT__44Ex: ;

}
// $ANTLR end T__44

//   Comes from: 27:7: ( 'yarn' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__45
 *
 * Looks to match the characters the constitute the token T__45
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__45(prnbwLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__45;
       
    
    // rnbw.g:27:7: ( 'yarn' )
    // rnbw.g:27:9: 'yarn'
    {
        MATCHS(lit_21); 
        if  (HASEXCEPTION())
        {
            goto ruleT__45Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__45Ex; /* Prevent compiler warnings */
    ruleT__45Ex: ;

}
// $ANTLR end T__45

//   Comes from: 28:7: ( 'edges' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__46
 *
 * Looks to match the characters the constitute the token T__46
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__46(prnbwLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__46;
       
    
    // rnbw.g:28:7: ( 'edges' )
    // rnbw.g:28:9: 'edges'
    {
        MATCHS(lit_22); 
        if  (HASEXCEPTION())
        {
            goto ruleT__46Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__46Ex; /* Prevent compiler warnings */
    ruleT__46Ex: ;

}
// $ANTLR end T__46

//   Comes from: 29:7: ( ',' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__47
 *
 * Looks to match the characters the constitute the token T__47
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__47(prnbwLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__47;
       
    
    // rnbw.g:29:7: ( ',' )
    // rnbw.g:29:9: ','
    {
        MATCHC(','); 
        if  (HASEXCEPTION())
        {
            goto ruleT__47Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__47Ex; /* Prevent compiler warnings */
    ruleT__47Ex: ;

}
// $ANTLR end T__47

//   Comes from: 30:7: ( 'from' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__48
 *
 * Looks to match the characters the constitute the token T__48
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__48(prnbwLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__48;
       
    
    // rnbw.g:30:7: ( 'from' )
    // rnbw.g:30:9: 'from'
    {
        MATCHS(lit_23); 
        if  (HASEXCEPTION())
        {
            goto ruleT__48Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__48Ex; /* Prevent compiler warnings */
    ruleT__48Ex: ;

}
// $ANTLR end T__48

//   Comes from: 31:7: ( 'including' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__49
 *
 * Looks to match the characters the constitute the token T__49
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__49(prnbwLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__49;
       
    
    // rnbw.g:31:7: ( 'including' )
    // rnbw.g:31:9: 'including'
    {
        MATCHS(lit_24); 
        if  (HASEXCEPTION())
        {
            goto ruleT__49Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__49Ex; /* Prevent compiler warnings */
    ruleT__49Ex: ;

}
// $ANTLR end T__49

//   Comes from: 32:7: ( 'not' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__50
 *
 * Looks to match the characters the constitute the token T__50
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__50(prnbwLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__50;
       
    
    // rnbw.g:32:7: ( 'not' )
    // rnbw.g:32:9: 'not'
    {
        MATCHS(lit_25); 
        if  (HASEXCEPTION())
        {
            goto ruleT__50Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__50Ex; /* Prevent compiler warnings */
    ruleT__50Ex: ;

}
// $ANTLR end T__50

//   Comes from: 33:7: ( '!' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__51
 *
 * Looks to match the characters the constitute the token T__51
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__51(prnbwLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__51;
       
    
    // rnbw.g:33:7: ( '!' )
    // rnbw.g:33:9: '!'
    {
        MATCHC('!'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__51Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__51Ex; /* Prevent compiler warnings */
    ruleT__51Ex: ;

}
// $ANTLR end T__51

//   Comes from: 34:7: ( 'to' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__52
 *
 * Looks to match the characters the constitute the token T__52
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__52(prnbwLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__52;
       
    
    // rnbw.g:34:7: ( 'to' )
    // rnbw.g:34:9: 'to'
    {
        MATCHS(lit_26); 
        if  (HASEXCEPTION())
        {
            goto ruleT__52Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__52Ex; /* Prevent compiler warnings */
    ruleT__52Ex: ;

}
// $ANTLR end T__52

//   Comes from: 35:7: ( 'back' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__53
 *
 * Looks to match the characters the constitute the token T__53
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__53(prnbwLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__53;
       
    
    // rnbw.g:35:7: ( 'back' )
    // rnbw.g:35:9: 'back'
    {
        MATCHS(lit_27); 
        if  (HASEXCEPTION())
        {
            goto ruleT__53Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__53Ex; /* Prevent compiler warnings */
    ruleT__53Ex: ;

}
// $ANTLR end T__53

//   Comes from: 36:7: ( 'and' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__54
 *
 * Looks to match the characters the constitute the token T__54
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__54(prnbwLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__54;
       
    
    // rnbw.g:36:7: ( 'and' )
    // rnbw.g:36:9: 'and'
    {
        MATCHS(lit_28); 
        if  (HASEXCEPTION())
        {
            goto ruleT__54Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__54Ex; /* Prevent compiler warnings */
    ruleT__54Ex: ;

}
// $ANTLR end T__54

//   Comes from: 37:7: ( '(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__55
 *
 * Looks to match the characters the constitute the token T__55
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__55(prnbwLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__55;
       
    
    // rnbw.g:37:7: ( '(' )
    // rnbw.g:37:9: '('
    {
        MATCHC('('); 
        if  (HASEXCEPTION())
        {
            goto ruleT__55Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__55Ex; /* Prevent compiler warnings */
    ruleT__55Ex: ;

}
// $ANTLR end T__55

//   Comes from: 38:7: ( '[' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__56
 *
 * Looks to match the characters the constitute the token T__56
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__56(prnbwLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__56;
       
    
    // rnbw.g:38:7: ( '[' )
    // rnbw.g:38:9: '['
    {
        MATCHC('['); 
        if  (HASEXCEPTION())
        {
            goto ruleT__56Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__56Ex; /* Prevent compiler warnings */
    ruleT__56Ex: ;

}
// $ANTLR end T__56

//   Comes from: 39:7: ( '->' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__57
 *
 * Looks to match the characters the constitute the token T__57
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__57(prnbwLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__57;
       
    
    // rnbw.g:39:7: ( '->' )
    // rnbw.g:39:9: '->'
    {
        MATCHS(lit_29); 
        if  (HASEXCEPTION())
        {
            goto ruleT__57Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__57Ex; /* Prevent compiler warnings */
    ruleT__57Ex: ;

}
// $ANTLR end T__57

//   Comes from: 40:7: ( '<->' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__58
 *
 * Looks to match the characters the constitute the token T__58
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__58(prnbwLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__58;
       
    
    // rnbw.g:40:7: ( '<->' )
    // rnbw.g:40:9: '<->'
    {
        MATCHS(lit_30); 
        if  (HASEXCEPTION())
        {
            goto ruleT__58Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__58Ex; /* Prevent compiler warnings */
    ruleT__58Ex: ;

}
// $ANTLR end T__58

//   Comes from: 41:7: ( '<i>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__59
 *
 * Looks to match the characters the constitute the token T__59
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__59(prnbwLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__59;
       
    
    // rnbw.g:41:7: ( '<i>' )
    // rnbw.g:41:9: '<i>'
    {
        MATCHS(lit_31); 
        if  (HASEXCEPTION())
        {
            goto ruleT__59Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__59Ex; /* Prevent compiler warnings */
    ruleT__59Ex: ;

}
// $ANTLR end T__59

//   Comes from: 42:7: ( '<n>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__60
 *
 * Looks to match the characters the constitute the token T__60
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__60(prnbwLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__60;
       
    
    // rnbw.g:42:7: ( '<n>' )
    // rnbw.g:42:9: '<n>'
    {
        MATCHS(lit_32); 
        if  (HASEXCEPTION())
        {
            goto ruleT__60Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__60Ex; /* Prevent compiler warnings */
    ruleT__60Ex: ;

}
// $ANTLR end T__60

//   Comes from: 43:7: ( ')' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__61
 *
 * Looks to match the characters the constitute the token T__61
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__61(prnbwLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__61;
       
    
    // rnbw.g:43:7: ( ')' )
    // rnbw.g:43:9: ')'
    {
        MATCHC(')'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__61Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__61Ex; /* Prevent compiler warnings */
    ruleT__61Ex: ;

}
// $ANTLR end T__61

//   Comes from: 44:7: ( ']' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__62
 *
 * Looks to match the characters the constitute the token T__62
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__62(prnbwLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__62;
       
    
    // rnbw.g:44:7: ( ']' )
    // rnbw.g:44:9: ']'
    {
        MATCHC(']'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__62Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__62Ex; /* Prevent compiler warnings */
    ruleT__62Ex: ;

}
// $ANTLR end T__62

//   Comes from: 129:3: ( ( 'a' .. 'z' | 'A' .. 'Z' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '-' )* )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start ID
 *
 * Looks to match the characters the constitute the token ID
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mID(prnbwLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = ID;
       
    
    // rnbw.g:129:3: ( ( 'a' .. 'z' | 'A' .. 'Z' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '-' )* )
    // rnbw.g:129:5: ( 'a' .. 'z' | 'A' .. 'Z' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '-' )*
    {
        if ( ((LA(1) >= 'A') && (LA(1) <= 'Z')) || ((LA(1) >= 'a') && (LA(1) <= 'z')) )
        {
            CONSUME();

        }
        else 
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();    goto ruleIDEx;
        }


        // rnbw.g:129:25: ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '-' )*

        for (;;)
        {
            int alt1=2;
            switch ( LA(1) ) 
            {
            case '-':
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'G':
            case 'H':
            case 'I':
            case 'J':
            case 'K':
            case 'L':
            case 'M':
            case 'N':
            case 'O':
            case 'P':
            case 'Q':
            case 'R':
            case 'S':
            case 'T':
            case 'U':
            case 'V':
            case 'W':
            case 'X':
            case 'Y':
            case 'Z':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
            case 'g':
            case 'h':
            case 'i':
            case 'j':
            case 'k':
            case 'l':
            case 'm':
            case 'n':
            case 'o':
            case 'p':
            case 'q':
            case 'r':
            case 's':
            case 't':
            case 'u':
            case 'v':
            case 'w':
            case 'x':
            case 'y':
            case 'z':
            	{
            		alt1=1;
            	}
                break;

            }

            switch (alt1) 
            {
        	case 1:
        	    // rnbw.g:
        	    {
        	        if ( LA(1) == '-' || ((LA(1) >= '0') && (LA(1) <= '9')) || ((LA(1) >= 'A') && (LA(1) <= 'Z')) || ((LA(1) >= 'a') && (LA(1) <= 'z')) )
        	        {
        	            CONSUME();

        	        }
        	        else 
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();    goto ruleIDEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop1;	/* break out of the loop */
        	    break;
            }
        }
        loop1: ; /* Jump out to here if this rule does not match */


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleIDEx; /* Prevent compiler warnings */
    ruleIDEx: ;

}
// $ANTLR end ID

//   Comes from: 131:4: ( ( '0' .. '9' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start INT
 *
 * Looks to match the characters the constitute the token INT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mINT(prnbwLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = INT;
       
    
    // rnbw.g:131:4: ( ( '0' .. '9' )+ )
    // rnbw.g:131:6: ( '0' .. '9' )+
    {
        // rnbw.g:131:6: ( '0' .. '9' )+
        {
            int cnt2=0;

            for (;;)
            {
                int alt2=2;
        	switch ( LA(1) ) 
        	{
        	case '0':
        	case '1':
        	case '2':
        	case '3':
        	case '4':
        	case '5':
        	case '6':
        	case '7':
        	case '8':
        	case '9':
        		{
        			alt2=1;
        		}
        	    break;

        	}

        	switch (alt2) 
        	{
        	    case 1:
        	        // rnbw.g:131:6: '0' .. '9'
        	        {
        	            MATCHRANGE('0', '9'); 
        	            if  (HASEXCEPTION())
        	            {
        	                goto ruleINTEx;
        	            }


        	        }
        	        break;

        	    default:
        	    
        		if ( cnt2 >= 1 )
        		{
        		    goto loop2;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleINTEx;
        	}
        	cnt2++;
            }
            loop2: ;	/* Jump to here if this rule does not match */
        }

    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleINTEx; /* Prevent compiler warnings */
    ruleINTEx: ;

}
// $ANTLR end INT

//   Comes from: 133:9: ( ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '-' | '!' | '@' | '#' | '$' | '%' | '^' | '&' | '(' | ')' | '+' | '=' | '_' | '~' | '.' | ',' | ':' | ' ' | '/' | ';' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start FILENAME
 *
 * Looks to match the characters the constitute the token FILENAME
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mFILENAME(prnbwLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = FILENAME;
       
    
    // rnbw.g:133:9: ( ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '-' | '!' | '@' | '#' | '$' | '%' | '^' | '&' | '(' | ')' | '+' | '=' | '_' | '~' | '.' | ',' | ':' | ' ' | '/' | ';' )+ )
    // rnbw.g:133:11: ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '-' | '!' | '@' | '#' | '$' | '%' | '^' | '&' | '(' | ')' | '+' | '=' | '_' | '~' | '.' | ',' | ':' | ' ' | '/' | ';' )+
    {
        // rnbw.g:133:11: ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '-' | '!' | '@' | '#' | '$' | '%' | '^' | '&' | '(' | ')' | '+' | '=' | '_' | '~' | '.' | ',' | ':' | ' ' | '/' | ';' )+
        {
            int cnt3=0;

            for (;;)
            {
                int alt3=2;
        	switch ( LA(1) ) 
        	{
        	case ' ':
        	case '!':
        	case '#':
        	case '$':
        	case '%':
        	case '&':
        	case '(':
        	case ')':
        	case '+':
        	case ',':
        	case '-':
        	case '.':
        	case '/':
        	case '0':
        	case '1':
        	case '2':
        	case '3':
        	case '4':
        	case '5':
        	case '6':
        	case '7':
        	case '8':
        	case '9':
        	case ':':
        	case ';':
        	case '=':
        	case '@':
        	case 'A':
        	case 'B':
        	case 'C':
        	case 'D':
        	case 'E':
        	case 'F':
        	case 'G':
        	case 'H':
        	case 'I':
        	case 'J':
        	case 'K':
        	case 'L':
        	case 'M':
        	case 'N':
        	case 'O':
        	case 'P':
        	case 'Q':
        	case 'R':
        	case 'S':
        	case 'T':
        	case 'U':
        	case 'V':
        	case 'W':
        	case 'X':
        	case 'Y':
        	case 'Z':
        	case '^':
        	case '_':
        	case 'a':
        	case 'b':
        	case 'c':
        	case 'd':
        	case 'e':
        	case 'f':
        	case 'g':
        	case 'h':
        	case 'i':
        	case 'j':
        	case 'k':
        	case 'l':
        	case 'm':
        	case 'n':
        	case 'o':
        	case 'p':
        	case 'q':
        	case 'r':
        	case 's':
        	case 't':
        	case 'u':
        	case 'v':
        	case 'w':
        	case 'x':
        	case 'y':
        	case 'z':
        	case '~':
        		{
        			alt3=1;
        		}
        	    break;

        	}

        	switch (alt3) 
        	{
        	    case 1:
        	        // rnbw.g:
        	        {
        	            if ( ((LA(1) >= ' ') && (LA(1) <= '!')) || ((LA(1) >= '#') && (LA(1) <= '&')) || ((LA(1) >= '(') && (LA(1) <= ')')) || ((LA(1) >= '+') && (LA(1) <= ';')) || LA(1) == '=' || ((LA(1) >= '@') && (LA(1) <= 'Z')) || ((LA(1) >= '^') && (LA(1) <= '_')) || ((LA(1) >= 'a') && (LA(1) <= 'z')) || LA(1) == '~' )
        	            {
        	                CONSUME();

        	            }
        	            else 
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();    goto ruleFILENAMEEx;
        	            }


        	        }
        	        break;

        	    default:
        	    
        		if ( cnt3 >= 1 )
        		{
        		    goto loop3;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleFILENAMEEx;
        	}
        	cnt3++;
            }
            loop3: ;	/* Jump to here if this rule does not match */
        }

    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleFILENAMEEx; /* Prevent compiler warnings */
    ruleFILENAMEEx: ;

}
// $ANTLR end FILENAME

//   Comes from: 135:3: ( ( ' ' | '\\t' | '\\r' | '\\n' ) )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start WS
 *
 * Looks to match the characters the constitute the token WS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mWS(prnbwLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = WS;
       
    
    // rnbw.g:135:3: ( ( ' ' | '\\t' | '\\r' | '\\n' ) )
    // rnbw.g:135:5: ( ' ' | '\\t' | '\\r' | '\\n' )
    {
        if ( ((LA(1) >= '\t') && (LA(1) <= '\n')) || LA(1) == '\r' || LA(1) == ' ' )
        {
            CONSUME();

        }
        else 
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();    goto ruleWSEx;
        }

        {
            LEXSTATE->channel=HIDDEN;
        }

    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleWSEx; /* Prevent compiler warnings */
    ruleWSEx: ;

}
// $ANTLR end WS

/** This is the entry point in to the lexer from an object that
 *  wants to generate the next token, such as a pCOMMON_TOKEN_STREAM
 */
static void 
mTokens(prnbwLexer ctx)
{
    {
        //  rnbw.g:1:8: ( T__25 | T__26 | T__27 | T__28 | T__29 | T__30 | T__31 | T__32 | T__33 | T__34 | T__35 | T__36 | T__37 | T__38 | T__39 | T__40 | T__41 | T__42 | T__43 | T__44 | T__45 | T__46 | T__47 | T__48 | T__49 | T__50 | T__51 | T__52 | T__53 | T__54 | T__55 | T__56 | T__57 | T__58 | T__59 | T__60 | T__61 | T__62 | ID | INT | FILENAME | WS )
        
        ANTLR3_UINT32 alt4;

        alt4=42;

        alt4 = cdfa4.predict(ctx, RECOGNIZER, ISTREAM, &cdfa4);
        if  (HASEXCEPTION())
        {
            goto ruleTokensEx;
        }

        switch (alt4) 
        {
    	case 1:
    	    // rnbw.g:1:10: T__25
    	    {
    	        /* 1:10: T__25 */
    	        mT__25(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 2:
    	    // rnbw.g:1:16: T__26
    	    {
    	        /* 1:16: T__26 */
    	        mT__26(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 3:
    	    // rnbw.g:1:22: T__27
    	    {
    	        /* 1:22: T__27 */
    	        mT__27(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 4:
    	    // rnbw.g:1:28: T__28
    	    {
    	        /* 1:28: T__28 */
    	        mT__28(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 5:
    	    // rnbw.g:1:34: T__29
    	    {
    	        /* 1:34: T__29 */
    	        mT__29(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 6:
    	    // rnbw.g:1:40: T__30
    	    {
    	        /* 1:40: T__30 */
    	        mT__30(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 7:
    	    // rnbw.g:1:46: T__31
    	    {
    	        /* 1:46: T__31 */
    	        mT__31(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 8:
    	    // rnbw.g:1:52: T__32
    	    {
    	        /* 1:52: T__32 */
    	        mT__32(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 9:
    	    // rnbw.g:1:58: T__33
    	    {
    	        /* 1:58: T__33 */
    	        mT__33(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 10:
    	    // rnbw.g:1:64: T__34
    	    {
    	        /* 1:64: T__34 */
    	        mT__34(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 11:
    	    // rnbw.g:1:70: T__35
    	    {
    	        /* 1:70: T__35 */
    	        mT__35(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 12:
    	    // rnbw.g:1:76: T__36
    	    {
    	        /* 1:76: T__36 */
    	        mT__36(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 13:
    	    // rnbw.g:1:82: T__37
    	    {
    	        /* 1:82: T__37 */
    	        mT__37(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 14:
    	    // rnbw.g:1:88: T__38
    	    {
    	        /* 1:88: T__38 */
    	        mT__38(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 15:
    	    // rnbw.g:1:94: T__39
    	    {
    	        /* 1:94: T__39 */
    	        mT__39(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 16:
    	    // rnbw.g:1:100: T__40
    	    {
    	        /* 1:100: T__40 */
    	        mT__40(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 17:
    	    // rnbw.g:1:106: T__41
    	    {
    	        /* 1:106: T__41 */
    	        mT__41(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 18:
    	    // rnbw.g:1:112: T__42
    	    {
    	        /* 1:112: T__42 */
    	        mT__42(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 19:
    	    // rnbw.g:1:118: T__43
    	    {
    	        /* 1:118: T__43 */
    	        mT__43(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 20:
    	    // rnbw.g:1:124: T__44
    	    {
    	        /* 1:124: T__44 */
    	        mT__44(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 21:
    	    // rnbw.g:1:130: T__45
    	    {
    	        /* 1:130: T__45 */
    	        mT__45(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 22:
    	    // rnbw.g:1:136: T__46
    	    {
    	        /* 1:136: T__46 */
    	        mT__46(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 23:
    	    // rnbw.g:1:142: T__47
    	    {
    	        /* 1:142: T__47 */
    	        mT__47(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 24:
    	    // rnbw.g:1:148: T__48
    	    {
    	        /* 1:148: T__48 */
    	        mT__48(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 25:
    	    // rnbw.g:1:154: T__49
    	    {
    	        /* 1:154: T__49 */
    	        mT__49(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 26:
    	    // rnbw.g:1:160: T__50
    	    {
    	        /* 1:160: T__50 */
    	        mT__50(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 27:
    	    // rnbw.g:1:166: T__51
    	    {
    	        /* 1:166: T__51 */
    	        mT__51(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 28:
    	    // rnbw.g:1:172: T__52
    	    {
    	        /* 1:172: T__52 */
    	        mT__52(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 29:
    	    // rnbw.g:1:178: T__53
    	    {
    	        /* 1:178: T__53 */
    	        mT__53(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 30:
    	    // rnbw.g:1:184: T__54
    	    {
    	        /* 1:184: T__54 */
    	        mT__54(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 31:
    	    // rnbw.g:1:190: T__55
    	    {
    	        /* 1:190: T__55 */
    	        mT__55(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 32:
    	    // rnbw.g:1:196: T__56
    	    {
    	        /* 1:196: T__56 */
    	        mT__56(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 33:
    	    // rnbw.g:1:202: T__57
    	    {
    	        /* 1:202: T__57 */
    	        mT__57(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 34:
    	    // rnbw.g:1:208: T__58
    	    {
    	        /* 1:208: T__58 */
    	        mT__58(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 35:
    	    // rnbw.g:1:214: T__59
    	    {
    	        /* 1:214: T__59 */
    	        mT__59(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 36:
    	    // rnbw.g:1:220: T__60
    	    {
    	        /* 1:220: T__60 */
    	        mT__60(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 37:
    	    // rnbw.g:1:226: T__61
    	    {
    	        /* 1:226: T__61 */
    	        mT__61(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 38:
    	    // rnbw.g:1:232: T__62
    	    {
    	        /* 1:232: T__62 */
    	        mT__62(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 39:
    	    // rnbw.g:1:238: ID
    	    {
    	        /* 1:238: ID */
    	        mID(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 40:
    	    // rnbw.g:1:241: INT
    	    {
    	        /* 1:241: INT */
    	        mINT(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 41:
    	    // rnbw.g:1:245: FILENAME
    	    {
    	        /* 1:245: FILENAME */
    	        mFILENAME(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 42:
    	    // rnbw.g:1:254: WS
    	    {
    	        /* 1:254: WS */
    	        mWS(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;

        }
    }

    
    goto ruleTokensEx; /* Prevent compiler warnings */
ruleTokensEx: ;
}

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */
/* End of Lexer code
 * ================================================
 * ================================================
 */ 


/* End of code
 * =============================================================================
 */
